### ISSUE TITLE
Hangs on iex -S mix  with version 0.13.3

### ISSUE THREAD

**Issue by sb3rg** [bitwalker/libgraph#28] opened 2019-03-11 03:01 UTC

**Comment by bitwalker** [comment] 2019-07-02 04:14
I'm not able to reproduce, and I'm not sure that this is a libgraph issue anyway - it doesn't start anything, as it is a pure code library, and it doesn't do anything complex at compile-time that might result in a hang. If you can give me a repro case, I'll investigate further, but I'm going to close this for now.

**Closed by bitwalker** 2019-07-02 04:14 UTC
